version: '2'
services:
    selenium:
      image: selenium/standalone-firefox-debug:3.141.59
      ports:
        - 4444
        - 5900:5900
      volumes:
        - /dev/shm:/dev/shm
    k_learn_app:
        command: ["uvicorn", "app.main:app", "--reload", "--port", "8000", "--host", "0.0.0.0"]
        build: .
        volumes:
            - ./app/:/app
        ports:
            - 8000:8000
        platform: 'linux/amd64'
        depends_on:
            selenium:
                condition: service_started
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /app/.keys/k-learn-356308-750f03b3e3eb.json
        tty: true